/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // default: [{ type: "autogenerated", dirName: "." }],
  default: [
    {
      type: "doc",
      label: "Home",
      id: "home",
    },
    { type: "html", value: "<div />", className: "sidebar__divider" },
    {
      type: "category",
      label: "Docs",
      collapsed: false,
      items: [
        { type: "link", label: "Nodes", href: "/nodes" },
        { type: "link", label: "Design", href: "/nodes" },
        { type: "link", label: "Extension", href: "/nodes" },
      ],
    },
    // "hello",
    // {
    //   type: "category",
    //   label: "Tutorial",
    //   items: ["tutorial-basics/create-a-document"],
    // },
  ],
};

module.exports = sidebars;
